name: Danger Swift
on:
  pull_request:
    branches:
      - '**'
      - '!master'

jobs:
  danger:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v3
        with:
          path: /Users/${{ runner.username }}/Library/Caches/Homebrew
          key: homebrew-${{ runner.os }}-${{ hashFiles('**/*.rb') }}
          restore-keys: |
            homebrew-${{ runner.os }}-

      - name: Install Danger Swift
        run: |
          brew tap danger/tap
          brew install danger/tap/danger-swift

      - name: Run Danger Swift
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}