name: Danger
on:
  pull_request:
    branches:
      - '**'
      - '!master'
jobs:
  danger:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/swift@3.15.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}