name: Danger Swift
on:
  pull_request:
    branches:
      - '**'
      - '!master'

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  danger:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/Homebrew/Library/Homebrew
            /Users/${{ runner.username }}/Library/Caches/Homebrew
          key: homebrew-${{ runner.os }}-${{ hashFiles('**/*.rb') }}
          restore-keys: |
            homebrew-${{ runner.os }}-

      - name: Cache SwiftLint
        id: cache-swiftlint
        uses: actions/cache@v3
        with:
          path: /usr/local/Cellar/swiftlint
          key: swiftlint-${{ runner.os }}-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            swiftlint-${{ runner.os }}-

      - name: Install Danger Swift
        run: |
          brew tap danger/tap
          brew install swiftlint
          brew install danger/tap/danger-swift

      - name: Run Danger Swift
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
