name: Danger Swift
on:
  pull_request:
    branches:
      - '**'
      - '!master'

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  danger:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/foo--*
            ~/Library/Caches/Homebrew/downloads/*--foo-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: homebrew-

      - name: Install Danger Swift
        run: |
          brew install swiftlint
          brew tap danger/tap
          brew install danger/tap/danger-swift

      - name: Run Danger Swift
        run: danger-swift ci --fail-on-errors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
