name: Danger Swift

on: [pull_request]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  danger:
    name: Danger
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - run: bundle install

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger
